### ISSUE TITLE
Distributed GPU application (triangle-counting) can't build with CUDA capability 7.5

### ISSUE THREAD

**Issue by yuhc** [KatanaGraph/katana#111]
The issue is related to #72 . Previously I didn't compile Katana with `-DGALOIS_ENABLE_DIST=ON` and missed this error.
I used the following cmake arguments:

```
cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_CUDA_COMPILER="/usr/local/cuda-10.1/bin/nvcc" -DGALOIS_CUDA_CAPABILITY=7.5 -DGALOIS_ENABLE_AVA=ON -DGALOIS_ENABLE_DIST=ON ../katana
```

The build log:

```
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17617; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17622; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17627; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17632; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17637; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17666; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17710; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17714; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17718; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17722; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17726; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas /tmp/tmpxft_00009dff_00000000-5_tc_cuda.ptx, line 17755; error   : Instruction 'shfl' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
ptxas fatal   : Ptx assembly aborted due to errors
make[2]: *** [lonestar/analytics/distributed/triangle-counting/CMakeFiles/triangle-counting-dist_cuda.dir/tc_cuda.cu.o] Error 255
lonestar/analytics/distributed/triangle-counting/CMakeFiles/triangle-counting-dist_cuda.dir/build.make:79: recipe for target 'lonestar/analytics/distributed/triangle-counting/CMakeFiles/triangle-counting-dist_cuda.dir/tc_cuda.cu.o' failed
make[1]: *** [lonestar/analytics/distributed/triangle-counting/CMakeFiles/triangle-counting-dist_cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by vishweshjatala** [comment]
The issue is with moderngpu it has been fixed in https://github.com/IntelligentSoftwareSystems/Galois/pull/305. Please check it

**Comment by yuhc** [comment]
The previous merge fixed the code under `lonestar/analytics/gpu/`, but `lonestar/analytics/distributed/triangle-counting` still can't be compiled.
Can this workload be built in Galois?

**Comment by yuhc** [comment]
> The issue is with moderngpu it has been fixed in [IntelligentSoftwareSystems/Galois#305](https://github.com/IntelligentSoftwareSystems/Galois/pull/305). Please check it

Just found the moderngpu repo wasn't updated in Katana. The problem is solved after I checkout commit 2b39855. Thanks!
